---
title: "Oversigt og ressourcer"
---

R er et program udviklet til statistisk analyse, men kan nu bruges til en lang række formål, herunder laves apps, hjemmesider, 

En åbenlys fordel ved R i forhold til en lang række andre tilsvarende programmer (for eksempelvis SAS, Stata og SPSS) er at det er gratis. Derfor dukker R også typisk op som en mulighed når både private virksomheder og offentlige institutioner ser på omkostningerne forbundet med dyre licenser. R bruges i forskningsverdenen og kan samtidig tale sammen med andre open-source SQL-baserede databaser.

Denne side tjener som en inspiration og indgang til R. Siden er primært rettet mod ansatte i Staten, men meget information vil være generelt og kan benyttes af enhver, som er intresseret i at lære R - eller i hvert fald finde gode kilder til materiale. 

Man kan sagtens installere R og laver sine analyser uden at installere noget som helst andet. De fleste foretrække dog at bruge en IDE (Integrated Development Environment) og her er RStudio nok det mest populære. RStudio kan som udgangspunkt bruges gratis, selvom der også findes løsninger man kan betale for. Firmaet bag RStudio hedder i øvrigt RStudio.

Udover RStudio står folkene bag RStudio står bag en lang række ressourcer, som gør R nemmere og mere attraktivt at bruge. Det er eksempelvis pakker til datamanipulation, datavisualisering, machine learning, opsætning af hjemmesider og en lang række andre ting.


# Installation

R kan installeres gratis fra https://cran.r-project.org/ til både Linux, Mac og Windows. For ansatte i Staten vil Windows-installationen være den relevante. Den skal man dog anmode om adgang til at installere i sit Softwarecenter gennem Statens IT's Serviceportal ved at anmode om "Specialsoftware.

Det anbefales at man også får installeret RStudio, som kan downloades på RStudios hjemmeside: https://www.rstudio.com/products/rstudio/download/. Arbejder man i Staten skal man igen anmode Statens IT om mulighed for at installere RStudio gennem sit Softwarecenter. Når R og RStudio er installeret kan man blot åbne RStudio for at køre R.


# Kurser og interaktiv læring

Der findes en lang række muligheder for at tage kurser online. Der er voksende fokus på *interaktive* læringsformer, hvor man koder i browseren og dermed får prøvet nogle af de ting af, som men præsenteres for. Dette afsnit beskriver en række både gratis og betalt løsninger, hvor man kan lære mere om R.

## RStudio Education

RStudio har et væld af ressourcer. Udover cheatsheets og  gratis onlinebøger (som vi også kommer nærmere ind på senere), så ligger der er lang række videoer og interaktive tutorials på https://rstudio.cloud/learn/primers

RStudio har også lavet pakken `learnr`, som kan installeres og giver adgang til interaktive tutorial direkte i RStudio.

## Datacamp

Datacamp tilbyder kurser, hvor man får mindre oplæg af 3-5 minutters varighed afløst af kodnings-opgaver, hvor man får feedback, hvis man skriver sin kode forkert. Setup'et giver anledning til en blanding af teori og praksis, som giver et effektivt læringsudbytte.

Datacamp har en måneds gratis prøveperiode. Udover R er der også kurser i andre programmeringssprog dog primært Python og SQL (udover R)

## Coursera

Coursera udbyder gratis en række kurser i R, se eksempelvis "Data Science Specialization" fra John Hopkins University.

# Lærebøger

Hvis jeg skulle vælge én bog til at supplere læring i R skulle det være "R for Data Science". Hvis du vil lære R, så skim et kapitel hver uge og få et overblik over hvad man kan i R og hvordan det kan gøres.

## Data Science

### R for Data Science
https://r4ds.had.co.nz/

## Style guide

Der er mange tilgange til hvordan man bør skrive kode på indenfor og på tværs af forskellige programmeringssprog. Det anbefales at man prøve at følge en "Best Practice". Der er mange gode fif til skrivestil, som både vil hjælpe dig selv og dine kollegaer, hvis i prøver at tilstræbe at følge tidyverse's styleguide:

https://style.tidyverse.org/


## Datavisualisering

Det mest populære grafik-system i R er ggplot2. Der findes dog en lang række forskellige pakker til datavisualisering. Nogle giver endda mulighed for at lave interaktive grafer. 

### ggplot2

I ggplot2-bogen præsenteres Hadley Wickham's populære plotting-system ggplot2. Bogen er relativt nem at komme igennem og udover at lære, hvordan man kan visualisere forskellige data, så præsenteres man også for, hvordan man kan lave gode visualiseringer. I 3-versions online-versionen er danskeren Thomas Lin Pedersen i øvrigt medforfatter.

https://ggplot2-book.org/

### Fundamental of Datavisualisation

Fundamentals of Datavisualisation præsenterer best-practice for data-visualisering på en lang række områder. Det er en god kilde at konsultere, hvis man vil hente inspiration til, hvordan man kan præsenterer sit data. Der er ikke noget R-kode i bogen, men man kan finde kildekoden til bogen på Github, hvis man vil prøve at reproducere nogle af figurerne.

https://clauswilke.com/dataviz/

### Data Visualization

Data visualization er en anden god kilde til hvordan man bør/ikke bør lave datavisualisering.

https://socviz.co/

### R Graphics Cookbook

I R Graphics Cookbook præsenteres en lang række "opskrifter" på hvordan man kan lave en lang række datavisualiseringer med ggplot2.

https://r-graphics.org/

### Interactive web-based datavisualisation with R, plotly, and shiny

Denne bog introducerer hvordan man kan lave interaktiv grafik med plotly og shiny.

https://plotly-r.com/


## Statistik

### Forecasting: Principles and Practice

Bogen præsenterer en lang række populære tidsserie-metode, herunder tidsserie-regressions, exponential smoothing og ARIMA-modeller.

https://otexts.com/fpp2/

### Introduction to Econometrics with R

Bogen indeholder en lang række af de samme ting som man eksempelvis finder i Wooldrigdes populære "Introductory Econometrics". Herudover er der også interaktive øvelser i bogen, hvor man koder direkte i bogen.

https://www.econometrics-with-r.org/

###  Causal inference

### Statistical Inference via Data Science

Bogen præsenterer statistisk inference med R.

https://moderndive.com/

### Causal inference: The mixtape

Bog præsenterer værktøjer til kausal inferens i den socialvidenskabelige forskning. Bogen har kodeeksempler i både R og Stata

https://mixtape.scunning.com/


```{r, eval=FALSE, echo=FALSE}
https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1268/2021/03/ciwhatif_hernanrobins_30mar21.pdf

```




## Machine Learning

Bogen præsenterer workflowet når man lave machine learning. Særligt kaptel 1-3 kan anbefales, hvis man vil prøve at få et overblik over workflowet og modellerings-processen når man lavet machine learning. Herudover beskriver bogen, forskellige strategier til feature-engineering og variabel-selektion, som kan forbedre ens modellers prædiktionsevne. Bogen beskriver dog ikke forskellige machine learning algoritmer i detaljer. Bogen er lavet i R, men der er ikke R-kode i bogen.

Feature Engineering and Selection: A Practical Approach for Predictive Models 
http://www.feat.engineering/

### Tidy Modeling with R

https://www.tmwr.org/

An Introduction to statistical Learning
https://www.statlearning.com/ (gratis pdf på hjemmesiden)


Tip: Hvis du er interesseret i prædiktiv modellering / machine learning, så læs kapitel 1-3 for et overblik over modelleringsprocessen. 

Targeted learning in R
https://tlverse.org/tlverse-handbook/index.html
Causal inference med machine learning

Interpretable Machine Learning 
https://christophm.github.io/interpretable-ml-book/

Exploratory Model Analysis
https://ema.drwhy.ai/

## Text mining

https://geocompr.robinlovelace.net/

## Rapportering (RMarkdown)

RMarkdown

https://bookdown.org/yihui/rmarkdown/

## Rmarkdown for Scientists

https://rmd4sci.njtierney.com/

### Skriv onlinebøger

https://bookdown.org/yihui/bookdown/

### Lav hjemmesider

https://bookdown.org/yihui/blogdown/

## Shiny

https://mastering-shiny.org/

https://engineering-shiny.org/

## Kort / Geocomputation

https://geocompr.robinlovelace.net/

## Avanceret programmering

Dybereluggnede koncepter i programmering 
https://adv-r.hadley.nz/

Efficient programmering i R
https://csgillespie.github.io/efficientR/

https://r-pkgs.org/ 

## Versionskontrol 

### Git og R

https://happygitwithr.com/#

### Git bogen

https://git-scm.com/book/en/v2

NB: Ikke specifikt relateret til R

### SVN

Ikke specifikt relateret til R

NB: http://svnbook.red-bean.com/

## Databaser og R

https://db.rstudio.com/

https://therinspark.com/

## Cheatsheats

## Big Book of R

En oversigt lignende denne, hvor man kan finde bøger om R og tilknyttede emner. Henviser dog også til betalte løsninger.

https://www.bigbookofr.com/
 